#!/bin/bash
# author: Morhunenko Mykola (Myralllka)
# change all camel case to snake case in files

awk -i inplace '{
  while ( match($0, /(.*)([a-z0-9])([A-Z])(.*)/, cap)) 
      $0 = cap[1] cap[2] "_" tolower(cap[3]) cap[4];
  
  print
}' $1
