#!/bin/bash

# author: I forgot, but some guy from forums =)
# Script to change window locale to fixed every time when switching windows.
# Almost like in Gnome3, but without saving locale for each window
# I use it because often I should switch from ua to en and vice versa, and with this script I know for sure that I will have English everywhere =)

i3subscribe window | \
while read -r line; do
	if [ "$line" = 'window:focus' ]; then
		echo here $line
    id="$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}')"
    case "$(xprop -id "$id" WM_CLASS | cut -d\" -f4)" in
	chromium)       kb=us;;
	terminology)    kb=us;;
        *)          kb=us;;
    esac
    xkb-switch -s $kb
fi;
done
